export const GENRES = [
  "Rock",
  "Electronic",
  "Pop",
  "Jazz",
  "Funk / Soul",
  "Hip Hop",
  "Classical",
  "Latin",
  "Reggae",
  "Stage & Screen",
  "Blues",
  "Non-Music",
  "Children's",
  "Folk, World, & Country"
];

export const STYLES = [
  "House",
  "Techno",
  "Indie Rock",
  "Pop Rock",
  "Soul",
  "Disco",
  "Ambient",
  "Experimental",
  "Electro",
  "Trance",
  "Hardcore",
  "Drum n Bass",
  "Jazz-Funk",
  "Synth-pop",
  "Heavy Metal",
  "Punk",
  "Folk Rock",
  "Psychedelic Rock",
  "Blues Rock",
  "Alternative Rock",
  "Deep House",
  "Minimal",
  "Dubstep",
  "Garage Rock",
  "New Wave",
  "Post-Punk",
  "Goth Rock",
  "Shoegaze",
  "Dream Pop",
  "Trip Hop",
  "Big Beat",
  "IDM",
  "Glitch",
  "Noise",
  "Industrial",
  "EBM",
  "Ska",
  "Dub",
  "Rocksteady",
  "Roots Reggae",
  "Dancehall",
  "Bossa Nova",
  "Samba",
  "MPB",
  "Flamenco",
  "Tango",
  "Afrobeat",
  "Highlife",
  "Krautrock",
  "Space Rock",
  "Stoner Rock",
  "Sludge",
  "Doom Metal",
  "Black Metal",
  "Death Metal",
  "Thrash",
  "Grindcore",
  "Emo",
  "Hardcore Punk",
  "Screamo",
  "Math Rock",
  "Post-Rock",
  "Lo-Fi",
  "Vaporwave",
  "City Pop"
];

export const COUNTRIES = [
  "US",
  "UK",
  "Germany",
  "France",
  "Italy",
  "Japan",
  "Canada",
  "Australia",
  "Netherlands",
  "Spain",
  "Sweden",
  "Brazil",
  "Belgium",
  "Russia",
  "Greece",
  "Finland",
  "Norway",
  "Denmark",
  "Poland",
  "Austria",
  "Switzerland",
  "Mexico",
  "Argentina",
  "Jamaica",
  "Ireland",
  "Portugal",
  "New Zealand",
  "Hungary",
  "Czech Republic",
  "South Korea",
  "Turkey",
  "Yugoslavia",
  "USSR",
  "Colombia",
  "Venezuela",
  "Chile",
  "Peru",
  "South Africa",
  "India",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Taiwan",
  "Hong Kong",
  "China",
  "Malaysia",
  "Singapore",
  "Israel",
  "Egypt",
  "Lebanon",
  "Ukraine",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Iceland"
];

export const DECADES = [
  { label: "All Eras", value: "" },
  { label: "2020s", value: "202" },
  { label: "2010s", value: "201" },
  { label: "2000s", value: "200" },
  { label: "1990s", value: "199" },
  { label: "1980s", value: "198" },
  { label: "1970s", value: "197" },
  { label: "1960s", value: "196" },
  { label: "1950s", value: "195" },
];
